version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libya_alyoum_app
    network_mode: "host"
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - PORT=3009
    env_file:
      - .env
    restart: always
