version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libya_alyoum_app
    ports:
      - "3009:3009"
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - PORT=3009
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    restart: always
