version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: libya_alyoum_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: libyaalyoum
    volumes:
      - libya_alyoum_pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libya_alyoum_app
    ports:
      - "3009:3009"
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - PORT=3009
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  libya_alyoum_pgdata:
